version: "3.7"

services:

  api-rest:
    image: my-api-image:v1.0
    hostname: api-rest
    extra_hosts:
      - "dbsrv:192.168.56.57" # database server
      - "develsrv:192.168.56.56" # devel server (for testing)
    ports:
      - "5000"
   
  load-balancer:
    image: my-loadbalancer:v2.0
    ports:
      - "80:80"
    depends_on:
      - api-rest
