---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    mariadb_use_official_repo: true
    mariadb_use_official_repo_url: https://deb.mariadb.org
    mariadb_use_official_repo_version: 10.5
  vars_files: vars/testvars.yml

  roles:
    - role: ansible-role-mariadb
