- name: 1-install common properties and other tools
  apt:
    name:
      - software-properties-common
      - dirmngr
      - apt-transport-https
      - python3-pip
    state: present
    update_cache: yes
    
- name: 2-make sure that pymysql is present
  pip:
    name: pymysql
    state: present

- name: 3-add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "0xF1656F24C74CD1D8"

- name: 4-add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el,s390x] https://mirror.realcompute.io/mariadb/repo/10.6/ubuntu focal main
    state: present

- name: 5-install mariadb
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: yes

- name: 6-allow remote access to mariadb
  blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      skip-networking=0
      skip-bind-address

- name: 7-restart mariadb service
  service:
    name: mariadb
    state: restarted

- name: 8-stop mariadb
  service: name=mariadb state=stopped
    
- name: 9-set environment variables
  shell: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables --skip-networking"

- name: 10-start mariadb
  service: name=mariadb state=started

- name: 11-sql query flush privileges
  command:  mysql -u root --execute="FLUSH PRIVILEGES"

#TODO task non idempotent
- name: 12-sql query to connect without password
  command:  mysql -u root --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mariadb_password }}';"

- name: 13-stop mariadb
  service: name=mariadb state=stopped

- name: 14-unset environment variables
  shell: systemctl unset-environment MYSQLD_OPTS

- name: 15-start mariadb
  service: name=mariadb state=started

- name: 16-create a new database
  mysql_db:
    name: "{{ mariadb_test_database }}"
    login_user: "{{ mariadb_root_user }}"
    login_password: "{{ mariadb_password }}"
    state: present

- name: 17-insert sample data into database  
  mysql_db: 
    name: "{{ mariadb_test_database }}"
    state: import
    target: /vagrant/dump.sql 
    login_user: "{{ mariadb_root_user }}"
    login_password: "{{ mariadb_password }}"

- name: 18-create database user
  mysql_user:
    login_user: "{{ mariadb_root_user }}"
    login_password: "{{ mariadb_password }}"
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    host: "%"
    priv: '*.*:ALL'
    state: present