---
- name: Install cron package
  ansible.builtin.apt:
    package:
      - cron
    state: present

- name: Deploy DB dump script
  ansible.builtin.copy:
    src: mariadb_dump_db.sh
    dest: /usr/local/bin/mariadb_dump_db.sh
    owner: root
    group: root
    mode: 0744
    validate: "bash -n %s"

- name: Ensure backup dir exists
  ansible.builtin.file:
    path: "{{ mariadb_backup_db_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy crontab file
  ansible.builtin.cron:
    name: "Dump MariaDB databases"
    minute: "{{ mariadb_backup_db_cron_min }}"
    hour: "{{ mariadb_backup_db_cron_hour }}"
    job: "/usr/local/bin/mariadb_dump_db.sh \
      -d \"{{ mariadb_backup_db_dir }}\" \
      -l \"{{ mariadb_backup_db_name|join(',') }}\" \
      -k {{ mariadb_backup_db_rotation }} \
      {{ mariadb_backup_cron_std_output }} {{ mariadb_backup_db_dir }}/mariadb_dump_db.log"
    cron_file: mariadb_dump_db
    user: root
